# Generated by Django 4.0.3 on 2022-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField(default=False)),
                ('toggle', models.BooleanField(default=False)),
            ],
        ),
    ]
