# Generated by Django 4.0.3 on 2022-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todo_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Toggle',
            field=models.BooleanField(default=False),
        ),
    ]
